ERROR - 2023-12-02 16:44:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'useradmin'@'localhost' (using password: YES) in F:\x\Fundamentos de Base de Datos\app01\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 F:\x\Fundamentos de Base de Datos\app01\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'useradmin', Object(SensitiveParameterValue), 'tienda', 3306, '', 0)
#1 F:\x\Fundamentos de Base de Datos\app01\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 F:\x\Fundamentos de Base de Datos\app01\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 F:\x\Fundamentos de Base de Datos\app01\app\Controllers\ConsultasController.php(11): CodeIgniter\Database\BaseConnection->query('select * from n...')
#4 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(942): App\Controllers\ConsultasController->index()
#5 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultasController))
#6 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 F:\x\Fundamentos de Base de Datos\app01\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 F:\x\Fundamentos de Base de Datos\app01\system\Commands\Server\rewrite.php(47): require_once('F:\\x\\Fundamento...')
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in F:\x\Fundamentos de Base de Datos\app01\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 F:\x\Fundamentos de Base de Datos\app01\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 F:\x\Fundamentos de Base de Datos\app01\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 F:\x\Fundamentos de Base de Datos\app01\app\Controllers\ConsultasController.php(11): CodeIgniter\Database\BaseConnection->query('select * from n...')
#3 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(942): App\Controllers\ConsultasController->index()
#4 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultasController))
#5 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 F:\x\Fundamentos de Base de Datos\app01\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 F:\x\Fundamentos de Base de Datos\app01\system\Commands\Server\rewrite.php(47): require_once('F:\\x\\Fundamento...')
#8 {main}
CRITICAL - 2023-12-02 16:44:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\ConsultasController.php(11): CodeIgniter\Database\BaseConnection->query('select * from news')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ConsultasController->index()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultasController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('F:\\x\\Fundamentos de Base de Datos\\app01\\public\\index.php')
ERROR - 2023-12-02 16:52:36 --> mysqli_sql_exception: Table 'tienda.news' doesn't exist in F:\x\Fundamentos de Base de Datos\app01\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 F:\x\Fundamentos de Base de Datos\app01\system\Database\MySQLi\Connection.php(306): mysqli->query('select * from n...', 0)
#1 F:\x\Fundamentos de Base de Datos\app01\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('select * from n...')
#2 F:\x\Fundamentos de Base de Datos\app01\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('select * from n...')
#3 F:\x\Fundamentos de Base de Datos\app01\app\Controllers\ConsultasController.php(11): CodeIgniter\Database\BaseConnection->query('select * from n...')
#4 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(942): App\Controllers\ConsultasController->index()
#5 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultasController))
#6 F:\x\Fundamentos de Base de Datos\app01\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 F:\x\Fundamentos de Base de Datos\app01\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 F:\x\Fundamentos de Base de Datos\app01\system\Commands\Server\rewrite.php(47): require_once('F:\\x\\Fundamento...')
#9 {main}
CRITICAL - 2023-12-02 16:52:36 --> Table 'tienda.news' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Controllers\ConsultasController.php(11): CodeIgniter\Database\BaseConnection->query('select * from news')
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ConsultasController->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultasController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('F:\\x\\Fundamentos de Base de Datos\\app01\\public\\index.php')
CRITICAL - 2023-12-02 17:01:59 --> Class "CodeIgniter\Database" not found
in APPPATH\Controllers\CategoriaController.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\CategoriaController->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CategoriaController))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('F:\\x\\Fundamentos de Base de Datos\\app01\\public\\index.php')
CRITICAL - 2023-12-02 17:23:49 --> Class "App\Models\CategoriaModel" not found
in APPPATH\Controllers\CategoriaController.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(914): App\Controllers\CategoriaController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('F:\\x\\Fundamentos de Base de Datos\\app01\\public\\index.php')
CRITICAL - 2023-12-02 17:28:32 --> Call to undefined function base_utl()
in APPPATH\Views\categorias\index.php on line 13.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('categorias/index', [], true)
 4 APPPATH\Controllers\CategoriaController.php(28): view('categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\CategoriaController->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CategoriaController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('F:\\x\\Fundamentos de Base de Datos\\app01\\public\\index.php')
